#!/bin/csh
#makeinput
#/dev/shm/uffegj

#KOPIER MARCS TIL $TMPDIR
# cp ..... $TMPDIR/
# cd $TMPDIR
# ...koer marcs...
# mv mxmodel.dat $CWD/...
# cd $CWD
# rm -rf $TMPDIR 
#
#

setenv CWD `pwd`
setenv TMPDIR `mktemp -p /dev/shm/ -u`
mkdir $TMPDIR
cp -r ./* $TMPDIR/.
cd $TMPDIR 


#***************************
cp mxms7a.input  mxms7.input
cp models/t20g45mol52K2.arciv arcivaaa.dat
./marcs_test7

mv mxmodel.dat     	$CWD/models/testing.dat 
mv arcivaab.dat    	$CWD/models/testing.arciv
#***************************

mv GGchem_ppel     	$CWD/GGchem_ppel
mv mxms7.output    	$CWD/mxms7.output
mv MOL2.dat        	$CWD/MOL2.dat
mv pp.dat        	$CWD/pp.dat
mv wlos.dat        	$CWD/wlos.dat

rm spectrum.dat
rm fort.*

rm -rf $TMPDIR
