#!/bin/csh
#makeinput
#/dev/shm/uffegj

#KOPIER MARCS TIL $TMPDIR
# cp ..... $TMPDIR/
# cd $TMPDIR
# ...koer marcs...
# mv mxmodel.dat $CWD/...
# cd $CWD
# rm -rf $TMPDIR 
#
#

setenv CWD `pwd`
setenv TMPDIR `mktemp -p /dev/shm/ -u`
mkdir $TMPDIR
cp -r ./* $TMPDIR/.
cd $TMPDIR 


#***************************
cp mxms7a.input  mxms7.input
cp models/t25g45mol52K2.arciv arcivaaa.dat
./marcs_test7

mv mxmodel.dat     	$CWD/models/t25g45mol52K2_gg.dat 
mv arcivaab.dat    	$CWD/models/t25g45mol52K2_gg.arciv
#***************************

mv GGchem_ppel     	$CWD/GGchem_ppel
mv mxms7.output    	$CWD/mxms7.output
mv MOL2.dat        	$CWD/MOL2.dat
mv test.dat        	$CWD/test.dat
mv pp.dat        	$CWD/pp.dat
mv wlos.dat        	$CWD/wlos.dat
mv GGchem_molpp.dat        	$CWD/GGchem_molpp.dat
mv GGchem_molsum.dat        	$CWD/GGchem_molsum.dat
mv PartialPressures.dat     	$CWD/PartialPressures.dat
mv runetest.dat     	$CWD/runetest.dat
mv allpp.dat     	$CWD/allpp.dat

rm spectrum.dat
rm fort.*

rm -rf $TMPDIR
